### ISSUE TITLE
Error: TypeError: only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-wwt#17]
```
battersby@athena:~/Google Drive/higal_cmz/compare_with_simulation/direct_from_MK$ glue
/Users/battersby/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/battersby/anaconda/lib/python2.7/site-packages/glue/qt/__init__.py:6: GlueDeprecationWarning: The glue.qt subpackage is deprecated - see the v0.7 release announcement for more details
  "announcement for more details", GlueDeprecationWarning)
WARNING:root:Message signing is disabled.  This is insecure and not recommended!
Cannot fetch attributes None and None
Cannot fetch attributes PRIMARY and None
Traceback (most recent call last):
  File "/Users/battersby/anaconda/lib/python2.7/site-packages/glue_wwt/viewer/data_viewer.py", line 162, in _update_all
    self._update_layer(l)
  File "/Users/battersby/anaconda/lib/python2.7/site-packages/glue_wwt/viewer/data_viewer.py", line 158, in _update_layer
    a.update()
  File "/Users/battersby/anaconda/lib/python2.7/site-packages/glue_wwt/viewer/layer_artist.py", line 63, in update
    cmd = circle(ra[i], dec[i], label, layer.style.color)
  File "/Users/battersby/anaconda/lib/python2.7/site-packages/glue_wwt/viewer/layer_artist.py", line 16, in circle
    'color': color, 'radius': radius}
TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by astrofrog** [comment]
I think this may no longer be relevant since this code doesn't exist anymore
