### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-wwt#60]
```
Traceback (most recent call last):
  File "/Users/tom/python/dagstuhl/lib/python3.7/site-packages/glue/external/echo/qt/connect.py", line 480, in update_prop
    setattr(self._instance, self._prop, data_wrapper.data)
  File "/Users/tom/python/dagstuhl/lib/python3.7/site-packages/glue/external/echo/core.py", line 266, in __setattr__
    self._notify_global(**{attribute: value})
  File "/Users/tom/python/dagstuhl/lib/python3.7/site-packages/glue/external/echo/core.py", line 261, in _notify_global
    callback(**kwargs)
  File "/Users/tom/python/dagstuhl/lib/python3.7/site-packages/glue_wwt/viewer/layer_artist.py", line 104, in _update_markers
    self.disable_invalid_attributes(self._viewer_state.dec_att)
AttributeError: 'WWTDataViewerState' object has no attribute 'dec_att'
```

**Comment by Carifio24** [comment]
This was fixed in #87.
